name: sstream
description: SStream is a simplified version of StreamController which holds the lastest value broadcasted.
version: 1.0.5
homepage: https://www.otoritech.com
repository: https://github.com/otoricode/sstream

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
